language: python
python:
  - "2.7"
  
install:
  - pip install xmltodict
  - pip install pymongo
  - pip install /home/travis/build/nvinzens/OATS/saltstack/oatsdbhelpers
  - pip install pytest
  - pip install --upgrade pip enum34

script:
  - pytest
