hosts:
  - host: 10.20.1.22
    port: 830
    username: ins
    password: ins@lab
  - host: 10.20.1.21
    port: 830
    username: ins
    password: ins@lab

subscriptions:
  - subscription:
      xpath: /if:interfaces-state/interface/statistics/out-discards
      period: 1000
      kafka_publish_topic: interfaces-out-discards
      kafka_streams_eval: true
      event_threshold_data:
        - value: 100000
        - operator: greater_than
        - kafka_event_topic: out-discards-events
        - event: streaming-telemetry/*/out-discard-event
        - data_xpaths:
          - xpath: /notification/push-update/datastore-contents-xml/interfaces-state/interface/name
          - xpath: /notification/push-update/datastore-contents-xml/interfaces-state/interface/statistics/out-discards