# Config for logging
# ------------------
# See http://docs.python.org/2.7/library/logging.config.html#configuration-dictionary-schema
logging:
  version: 1
  disable_existing_loggers: true
  # Configuring the default (root) logger is highly recommended
  root:
    level: DEBUG
    handlers: [logfile]
  loggers:
    # Logging from my application
    oats.main:
      level: DEBUG
      handlers: [logfile]
      qualname: oats
      propagate: false
    oats.telemetry:
      level: DEBUG
      handlers: [logfile]
      qualname: oats.telemetry
      propagate: false
    oats.kafka:
      level: DEBUG
      handlers: [logfile]
      qualname: oats.kafka
      propagate: false
    oats.kafka.helpers:
      level: DEBUG
      handlers: [logfile]
      qualname: oats.kafka
      propagate: false
    oats.api:
      level: DEBUG
      handlers: [logfile]
      qualname: oats.api
      propagate: false
    oats.netbox:
      level: DEBUG
      handlers: [logfile]
      qualname: oats.netbox
      propagate: false
    oats.influx:
      level: DEBUG
      handlers: [logfile]
      qualname: oats.influx
      propagate: false
    oats.psql:
      level: DEBUG
      handlers: [logfile]
      qualname: oats.psql
      propagate: false
  handlers:
    logfile:
      class: logging.handlers.RotatingFileHandler
      filename: /var/log/oats/logs
      formatter: simpleFormatter
      level: DEBUG
      maxBytes: 10485760
  formatters:
    simpleFormatter:
      class: logging.Formatter
      format: '%(name)s %(asctime)s %(levelname)s %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'