hosts:
  - host: 10.20.1.21
    port: 830
    username: ins
    password: ins@lab
    subscriptions:
      - subscription:
          xpath: /ip-sla-ios-xe-oper:ip-sla-stats/sla-oper-entry/stats/jitter/sd/avg
          kafka_publish_topic: ip-sla
          period: 1000
      - subscription:
          xpath: /memory-ios-xe-oper:memory-statistics/memory-statistic/used-memory
          period: 1000
          kafka_publish_topic: oats




