hosts:
  - host: 10.20.1.22
    port: 830
    username: ins
    password: ins@lab
    subscriptions:
        - subscription:
            xpath: /if:interfaces-state/interface/statistics/out-discards
            period: 1000
            kafka_publish_topic: interfaces-out-discards
  - host: 10.20.1.21
    port: 830
    username: ins
    password: ins@lab
    subscriptions:
        - subscription:
            xpath: /if:interfaces-state/interface/statistics/out-discards
            period: 1000
            kafka_publish_topic: interfaces-out-discards