hosts:
  - host: 10.20.1.21
    port: 830
    username: ins
    password: ins@lab
    subscriptions:
      - subscription:
          xpath: /ip-sla-ios-xe-oper:ip-sla-stats/sla-oper-entry/stats/jitter/sd/avg
          kafka_publish_topic: ip-sla
          period: 1000
  - host: 10.20.1.22
      port: 830
      username: ins
      password: ins@lab
      subscriptions:
        - subscription:
            xpath: /memory-ios-xe-oper:memory-statistics/memory-statistic/used-memory
            period: 1000
            kafka_publish_topic: oats
hosts:
  - host: 10.20.1.21
    port: 830
    username: user
    password: guest
    subscriptions:
      - subscription:
          xpath: /memory-ios-xe-oper:memory-statistics/memory-statistic/free-memory
          kafka_publish_topic: oats
          period: 1000
      - subscription:
          xpath: /memory-ios-xe-oper:memory-statistics/memory-statistic/used-memory
          kafka_publish_topic: oats2
          period: 990
  - host: 10.20.1.22
    port: 830
    username: user2
    password: guest2
    subscriptions:
      - subscription:
          xpath: /memory-ios-xe-oper:memory-statistics/memory-statistic/free-memory
          kafka_publish_topic: oats
          period: 1000


hosts:
  - host: 10.20.1.21
    port: 830
    username: ins
    password: ins@lab
    subscriptions:
        - subscription:
            xpath: /memory-ios-xe-oper:memory-statistics/memory-statistic/used-memory
            period: 1000
            kafka_publish_topic: oats
  - host: 10.20.1.22
    port: 830
    username: ins
    password: ins@lab
    subscriptions:
      - subscription:
          xpath: /memory-ios-xe-oper:memory-statistics/memory-statistic/used-memory
          period: 1000
          kafka_publish_topic: oats
      - subscription:
            xpath: /if:interfaces-state/interface/statistics/out-discards
            period: 1000
            kafka_publish_topic: interfaces-out-discards
