hosts:
  - host: 10.20.1.22
    port: 830
    username: ins
    password: ins@lab
    subscriptions:
        - subscription:
            xpath: /bgp-ios-xe-oper:bgp-state-data/neighbors/neighbor/prefix-activity/received
            period: 1000
            kafka_publish_topic: oats
